### ISSUE TITLE
Add main property/value to bower.json

### ISSUE THREAD

**Issue by changalberto** [HubSpot/tooltip#13]
Can someone please add ```"main": "tooltip.js"``` into ```bower.json``` so that wiredep can pick it up when we install it using ``bower install``

**Comment by geekjuice** [comment]
Thanks for using `Tooltip` (still I hope :sweat_smile: ). I recently pushed out some changes that fixed the incorrect `bower.json` and `package.json` files from this project. Let me know if you run into any issues though and I'll be more than happy to help :smile_cat:
