### ISSUE TITLE
Uncaught TypeError: Cannot read property 'close' of undefined 

### ISSUE THREAD

**Issue by agenteo** [HubSpot/tooltip#15]
Hi,

I've included tether (0.6.5), drop (0.2.9) and tooltip (0.2.6).

I get that error on my page:

```
Uncaught TypeError: Cannot read property 'close' of undefined 
```

any clue where it might be coming from?

Thanks

**Comment by antonioreyna** [comment]
I have that error, how you solved it?

**Comment by agenteo** [comment]
It's been too long I am sorry I don't recall what I did. I suspect it was entirely my fault and I missed a required file.
