### ISSUE TITLE
Add a Tooltip constructor option to change drop's classPrefix

### ISSUE THREAD

**Issue by slamborne** [HubSpot/tooltip#16]
If bootstrap and tether tooltip are both loaded (yeah, yeah, these things happen...), bootstrap will apply its `.tooltip` style to tether's drop element - mainly `opacity: 0`.
Since I didn't see any tether styles applied with `.tooltip` I just removed the class with javascript and it seems to work.

**Comment by geekjuice** [comment]
Sorry for the delay. That's actually not a bad idea. However, overriding the `.tooltip` styles is still probably the preferred method as it's the most flexible. That said, I'll look into whether having a configurable `classPrefix` is something that might be worthwhile. Or if you'd like to see this feature sooner, feel free to open a Pull Request and I'll be more than happy to take a look as soon as it's opened. :smiley_cat:
