### ISSUE TITLE
Undefined is not a function for `el.getBoundingClientRect()`

### ISSUE THREAD

**Issue by jayd3e** [HubSpot/tooltip#20]
I'm seeing something really odd where I'm receiving the follow error `Undefined is not a function` at this line: https://github.com/HubSpot/tooltip/blob/master/tooltip.js#L102.  It is happening as a result of `el` getting set to a #document-fragment for w/e reason.  Can't seem to find the origin of the issue.  I'm including Tooltip 0.6.5, setting `Tooltip.autoinit = false;`, and creating a tip like this:

```
this.tooltip = new Tooltip({
    'target': this.edit_file_upload_icon_el[0],
    'position': 'right middle'
});
```

**Comment by geekjuice** [comment]
Sorry for the late response. As long as the target exists and is a valid DOM element, `getBoundingClientRect()` should return correctly. I'd recommend revisiting when these tooltips are being created and wait until the element exists before doing so.
