### ISSUE TITLE
Default position is ignored

### ISSUE THREAD

**Issue by tschaub** [HubSpot/tooltip#22]
If the `data-tooltip-position` attribute is not provided on an element, the default position will not be applied.  In this case, `options.position` [is assigned `null`](https://github.com/HubSpot/tooltip/blob/103da12870c7b67fefea5d44e20a8fd0db37bc84/js/tooltip.js#L26-L28) which overrides the default position in the extend call.

**Comment by geekjuice** [comment]
Thanks for using `Tooltip`! I actually found this bug a while back too and was actually fixed some time ago in this [commit](https://github.com/HubSpot/tooltip/commit/721d7ef6153daf0a64bc9684fb7333ab4b1054a4). The changes have propagated into the new updates as well, so let me know if you still have issues and I'll be more than happy to help. :smile_cat:
