### ISSUE TITLE
Update published version on npm

### ISSUE THREAD

**Issue by tschaub** [HubSpot/tooltip#23]
Curious if you intend to continue publishing to the npm registry.  I'm hitting some issues with the current published version (v0.2.1) that look to be fixed by [recent changes](https://github.com/HubSpot/tooltip/compare/v0.2.1...v0.2.6).

**Comment by geekjuice** [comment]
Thanks for using `Tooltip`. I recently pushed some big updates that fixes these little issues. The npm package should also be updated as well so let me know if you run into any issues and I'll be more than happy to help :smile_cat:
