### ISSUE TITLE
Tether Error: Both element and target must be defined

### ISSUE THREAD

**Issue by slorber** [HubSpot/tooltip#27]
I'm using Browserify with TetherTooltip.
`require("tether-tooltip/tooltip");` works fine to get the code.

However, Tether gives me the error `Tether Error: Both element and target must be defined`

Versions are:

```
/*! tether-tooltip 0.2.6 */
/*! tether 0.6.5 */
```

Notice that I have this error even with the code sample

```
new Tooltip({
  target: targetElement,
  position: 'top left',
  content: "My awesome <b>content</b>.",
  classes: 'my-tether-theme'
});
```

I see in my debugger the call to `setOptions` with the attributes

```
options: Object
  classes: "my-tether-theme"
  content: "My awesome <b>content</b>."
  position: "top left"
  target: div.space-overview-shared-with-count
```

So is it a bug? At least I don't understand what I am supposed to pass as `element`

**Comment by Steve-Mc** [comment]
Any fix for this?
