### ISSUE TITLE
Support for require

### ISSUE THREAD

**Issue by Sendoushi** [HubSpot/tooltip#32]
Tooltip, Drop and Tether should have support for require. In my case, I don't really want those vars in the global window since it's a bad practice. I would prefer to use require and amd the three: Tooltip, Drop and Tether. From what I gather, Tether already does this.

I'll try and pull request this. The problem, from what I see, is Tether needing to access the window to get Tether or Drop. There should be some strategy like the Tether one to use whatever is available.

Correct me if I'm wrong.

**Comment by slorber** [comment]
+1

**Comment by geekjuice** [comment]
Thanks for using `Tooltip`. I recently pushed out some changes that should now help with this issue :smiley_cat: `Drop` and `Tooltip` now come without the `Tether` code prepended, so you can require each separately (as a module system should do). Feel free if you run into any issues though and I'll be more than happy to help!
