### ISSUE TITLE
Support tooltips that we can hover

### ISSUE THREAD

**Issue by slorber** [HubSpot/tooltip#40]
I use tooltip in a special way, as I mount ReactJS components inside the tooltip.

These tooltips have buttons inside.

I was able to make it work with:

```
.tooltip-element.tooltip-theme-arrows {
  pointer-events: none;
  &.tooltip-hoverable {
    pointer-events: auto;
  }
}
```

And by adding the `tooltip-hoverable` class.
Drop seems clever and does not close the tooltip when it's hovered.

It would be nice to add that option in default themes as well as in the tooltip API

**Comment by geekjuice** [comment]
Hmm, `tooltip` is basically an extension of `drop` (as I'm sure you know) which defaults set to assume you will use `tooltips` as `tooltips`. For your case, I would just suggest using `drop` which doesn't use `pointer-events: none` in the styles.

**Comment by slorber** [comment]
hmmm yes it seems so :) I didn"t think the tooltip code was so simple actually :)

**Comment by geekjuice** [comment]
Haha yup. The repo is basically just for the tooltip styles :sweat_smile:
