### ISSUE TITLE
position vs. attach

### ISSUE THREAD

**Issue by dandv** [HubSpot/tooltip#43]
The [docs](http://github.hubspot.com/tooltip/) initialize the tooltip with `position: 'top left'`, then go on to say

> When initializing, you may set the `attach` property.

Could the distinction between the two be clarified? Could combinations of `position` and `attach` cause the tooltip to overalp the target, as if tether `attachment` and `targetAttachment` were used directly?

**Comment by geekjuice** [comment]
I actually think that's a typo. AFAIK, there is no `attach` property and the explanation probably just meant `position`. Thanks for catching that!
