### ISSUE TITLE
a11y

### ISSUE THREAD

**Issue by thejameskyle** [HubSpot/tooltip#50]
It would be awesome if this library could follow a11y best practices. Basically:

When shown:

```html
<div aria-describedby="tooltip-1">A nice element</div>
<div id="tooltip-1" role="tooltip" aria-hidden="false">A nice tooltip</div>
```

When not shown:

```html
<div aria-describedby="tooltip-1">A nice element</div>
<div id="tooltip-1" role="tooltip" aria-hidden="true">A nice tooltip</div>
```

**Comment by TrevorBurnham** [comment]
@thejameskyle Excellent suggestion. I'm working on this, but it looks like adding attributes to the content is tricky right now due to some unexpected behavior in Drop: https://github.com/HubSpot/drop/issues/134

**Comment by thejameskyle** [comment]
Awesome, thank you so much for doing this
