### ISSUE TITLE
Error if target not attached to DOM at the time of Tooltip creation

### ISSUE THREAD

**Issue by bambuk6** [HubSpot/tooltip#55]
If the target element is not attached to DOM at the time of Tooltip creation, later (when the element is attached and visible), on hover, the following error shows up: 

Uncaught TypeError: el.getBoundingClientRect is not a function

In my scenario, I am creating an element in a callback (attaching Tooltip to it) that is later appended to DOM. This results in the the error shown above.

Is there a workaround?

**Versions**
Tooltip: 1.2.0
Drop: 1.4.2
Tether: 1.2.0

**Stack**
getBounds   @   tether.js:121
(anonymous function)    @   tether.js:1255
getBoundingRect @   tether.js:1269
(anonymous function)    @   tether.js:1357
position    @   tether.js:1335
position    @   tether.js:954
enable  @   tether.js:812
open    @   drop.js:428
(anonymous function)    @   drop.js:366

**Comment by geekjuice** [comment]
Seems like the underlying issue is coming from [`tether`](https://github.com/HubSpot/tether), so it may be better to file an issue there.
