### ISSUE TITLE
Naming conflict with Bootstrap 4-alpha

### ISSUE THREAD

**Issue by stewhouston** [HubSpot/tooltip#57]
Just a heads up that Bootstrap 4 has a .tooltip CSS class of its own that conflicts with tether-tooltip's. The net effect is tooltips not displaying with no discernible error. I tracked it down to the opacity being forced to 0 by Bootstrap. Easy CSS fixes from there, but an extra 20-40 minutes of tinkering to figure it out.

**Comment by geekjuice** [comment]
It's possible to generate styles with a different prefix by changing the prefix [here](https://github.com/HubSpot/tooltip/blob/master/src/css/tooltip-theme-arrows.sass#L6) and rebuilding the library.
